### ISSUE TITLE
Breaks custom protocol

### ISSUE THREAD

**Issue by adam-lynch** [murphydanger/gulp-minify-css#107]
A recent update has broken some of my CSS. This:

```css
div{background-image:url(app://abc.png)}
```

Get changed to this:

```css
div{background-image:url(app:/abc.png)}
```

**Comment by adam-lynch** [comment]
Just checked... fine with 1.1.0, broken with 1.1.1

**Comment by shinnn** [comment]
https://github.com/murphydanger/gulp-minify-css/issues/82#issuecomment-87196977

Thanks for trying to contribute to this project though.

**Comment by adam-lynch** [comment]
Bah... I should know better. Thanks. https://github.com/jakubpawlowicz/clean-css/issues/608

**Comment by adam-lynch** [comment]
Both 1.1.0 and 1.1.1 seem to pull down clean-css@3.3.3. Are you sure it couldn't be anything in this module yeah?

**Comment by shinnn** [comment]
Sorry I cannot understand what are you asking me. Do you know what a caret semver operator (`^`) means?

**Comment by adam-lynch** [comment]
Both would install clean-css@3.3.3, right? So now I'm thinking it's not
clean-css's fault.

**Comment by shinnn** [comment]
> Both would install clean-css@3.3.3

Definitely yes, and there's no problem with it. The package version bump of the gulp plugin doesn't always include dependency updates. We released v1.1.1 to fix https://github.com/murphydanger/gulp-minify-css/issues/89, not for clean-css version bump.

**Comment by adam-lynch** [comment]
Could you please try https://github.com/adam-lynch/gulp-minify-css-investigation? I'm still seeing it and after comparing the directories, the only real difference seems to be this module's `index.js`.

**Comment by shinnn** [comment]
@adam-lynch I found the root cause. https://github.com/jakubpawlowicz/clean-css/issues/608#issuecomment-113165051 That is why v1.1.0 works fine for you but v1.1.0 doesn't. Thanks for the detailed report and the example repo.

**Comment by adam-lynch** [comment]
:+1:
